#!/usr/bin/env groovy

// An example of a declarative syntax pipeline for running a maven build

pipeline {
    agent { label 'master' }
    tools {
        // The M3 maven tool must be already configured in
        // Manage Jenkins -> Global Tool Configuration -> Maven
        maven 'M3'
    }
    stages {
        stage('Clone sources') {
            steps {
                git 'https://github.com/JFrogDev/project-examples'
            }
        }
        stage('Maven build') {
            steps {
                sh 'cd maven-example; mvn -Dmaven.test.failure.ignore clean package'
            }
        }
        stage('Test report') {
            steps {
                junit 'maven-example/**/target/surefire-reports/TEST-*.xml'
            }
        }
        stage('Archive') {
            steps {
                archive 'maven-example/**/target/*.war'
            }
        }
    }
}
